#!/bin/sh
# hexiansheng@fiberhome.com.cn 2012-10-05
#update for mtk tianzhw@fiberhome.com.cn  2015-5-7
######################COMMON PATH######################
. /usr/init_scripts/env_para.sh

COMMON_CONF=/etc/fh_common.conf

#path of apcfg
APCFG=/var/wlan/apcfg
APCFG_5=/var/wlan/apcfg_5

#path of wlan script
WLAN_SHELL=`grep "APP_SHELL_PATH_WLAN" $COMMON_CONF | cut -d = -f 2`

#path of rtl8192cd.ko
MODULE_PATH=/lib/fhko
FHSHELL=/rom/fhshell/misc_shell
#path of iwpriv
WLAN_BIN=`grep "APP_PATH_WLAN" $COMMON_CONF | cut -d = -f 2`
IWPRIV_CMD=$WLAN_BIN/iwpriv

#path of wlan log
DEBUG_LOG=/var/wlan/log

DOWN_FILE=/var/wlan/.down_5g

######################COMMON PATH######################
VAP_MAX_INDEX=2

#. $APCFG_5
while read line; do
if echo "$line" | grep -q '=';then
    name=`echo ${line} | cut -d'=' -f1`
    value=`echo ${line} | cut -d'=' -f2`
    line=${name}=\"${value}\"
#	echo ${line}
    eval "$line"
fi
done < $APCFG_5

if [ "${WIFIENABLE}" = "0" ]; then
    echo "ap: WiFi module disabled"
    
	if [ -f ${DOWN_FILE} ]; then
		echo "wifi was down already..."
		exit 1
	fi
	touch ${DOWN_FILE}
	
	ifconfig rai0 down
###	brctl delif br0 rai0

	ifconfig rai1 down
###	brctl delif br0 rai1

	ifconfig rai2 down
###	brctl delif br0 rai2

	ifconfig rai3 down
###	brctl delif br0 rai3

	exit 1
fi

rm -f $DEBUG_LOG
touch $DEBUG_LOG

IWPRIV () {
	echo "$IWPRIV_CMD $@" >> $DEBUG_LOG
	$IWPRIV_CMD "$@"
}

DEBUG_WLAN() {
	echo "$@" >> $DEBUG_LOG
}

#? 5g的接口??
remove_modules() {
	if [ "${MODLIST}" != "" ]; then
###		brctl delif br0 rai0
###		brctl delif br0 rai1
###		brctl delif br0 rai2
###		brctl delif br0 rai3
		
		DEBUG_WLAN "rmmod $MODULE_PATH/mt7662e_ap.ko"
		rmmod $MODULE_PATH/mt7662e_ap.ko
	fi
}

#root ACL
set_root_acl() {
	#1 set acl mode -> 0:allow all;   1: white list;    2:bleak list
	IWPRIV wlan0 set_mib aclmode=$ACLCMD_0
	
	#2 add mac list
	if [ "$ACLCMD_0" = "1" -o "$ACLCMD_0" = "2" ];then
		#clear acl
		IWPRIV wlan0 set_mib aclnum=0
				
		#add mac list
		COUNT_MAC_ACL=`echo $ACLMAC_0 | awk -F ',' '{print NF-1}'`
		COUNT_ACL=0
		while [ ${COUNT_ACL} -le ${COUNT_MAC_ACL} ] 
		do
			let INDEX_ACL=${COUNT_ACL}+1
			ADDMAC_ACL=`echo $ACLMAC_0 | cut -f "${INDEX_ACL}" -d ","`
			if [ "$ADDMAC_ACL" != "" ]; then
				IWPRIV wlan0 set_mib acladdr=$ADDMAC_ACL
			fi
			let COUNT_ACL+=1
		done			
	fi
}




#config wifi here
if [ "${1}" = "up" ]; then
	if [ ! -f ${DOWN_FILE} ]; then
		echo "wifi 5G was up already..."
		exit 1
	fi
	rm -rf ${DOWN_FILE}
	
	if [ "$ENABLE_0" = "1" ]; then
		ifconfig rai0 up
###		brctl addif br0 rai0
	else
		echo "5G SSID 1 is Disable"
	fi
	
	if [ "$ENABLE_1" = "1" ]; then
		ifconfig rai1 up
###		brctl addif br0 rai1
	else
		echo "5G SSID 2 is Disable"
	fi

	if [ "$ENABLE_2" = "1" ]; then
		ifconfig rai2 up
###		brctl addif br0 rai2
	else
		echo "5G SSID 3 is Disable"
	fi
	
	if [ "$ENABLE_3" = "1" ]; then
		ifconfig rai3 up
###		brctl addif br0 rai3
	else
		echo "5G SSID 4 is Disable"
	fi
	
	if [ "$ENABLE_0" = "1" -o "$ENABLE_1" = "1" -o "$ENABLE_2" = "1" -o "$ENABLE_3" = "1" ]; then
		notify2 "WIFI_5" "UP"
		ip link set rai0 netns MNG		
		$OVS_VSCTL --may-exist add-port SDN-bridge rai0 -- set interface rai0 ofport_request=12
		$OVS_VSCTL set Port rai0 other_config:rstp-enable=true

		var=`ip netns exec MNG ifconfig -a |grep rai0`
		if [ "$var" = "" ]; then
			ip link set rai0 netns MNG
			$OVS_VSCTL --may-exist add-port SDN-bridge rai0 -- set interface rai0 ofport_request=12
			$OVS_VSCTL set Port rai0 other_config:rstp-enable=true
			ip netns exec MNG ifconfig rai0 up
		else
			ip netns exec MNG ifconfig rai0 down
			#sleep 2
			ip netns exec MNG ifconfig rai0 up
		fi
	fi
	
###	$FHSHELL/init_vlan_binding_rai.sh 
	
	#wps
	#DEBUG_WLAN "$WLAN_SHELL/set_wps.sh open"
#默认关闭WPS，只在按键时开启
#	$WLAN_SHELL/set_wps.sh open
	
elif [ "${1}" = "down" ]; then
	if [ -f ${DOWN_FILE} ]; then
		echo "wifi was down already..."
		exit 1
	fi
	touch ${DOWN_FILE}
	
	#bring down

#	if [ "$ENABLE_0" = "0" ]; then
		ifconfig rai0 down
###		brctl delif br0 rai0
#	else
#		echo "SSID 1 is Disable"
#	fi
	
#	if [ "$ENABLE_1" = "0" ]; then
		ifconfig rai1 down
###		brctl delif br0 rai1
#	else
#		echo "SSID 2 is Disable"
#	fi

#	if [ "$ENABLE_2" = "0" ]; then
		ifconfig rai2 down
###		brctl delif br0 rai2
#	else
#		echo "SSID 3 is Disable"
#	fi
	
#	if [ "$ENABLE_3" = "0" ]; then
		ifconfig rai3 down
###		brctl delif br0 rai3
#	else
#		echo "SSID 4 is Disable"
#	fi

	
	if [ "${2}" = "modules" ]; then
		remove_modules
	fi
	
	#wps
	#DEBUG_WLAN "$WLAN_SHELL/set_wps.sh close"
#默认关闭WPS，只在按键时开启
#	$WLAN_SHELL/set_wps.sh close

elif [ "${1}" = "show" ]; then
	$WLAN_SHELL/wifi_show.sh
else
    echo "ap: invalid argument"
    exit 1
fi

exit 0
